import { CommonModule } from '@angular/common';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ClaimApiService } from '../../core/services/claim-api.service';
import { FilingType } from '../../core/models/claim.model';

@Component({ standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink], template: `<main><a routerLink="/claims">← My claims</a><h1>Create a claim</h1><p>Submit property-dispute information. This does not make a legal decision or file court documents.</p><form [formGroup]="form" (ngSubmit)="submit()"><label>Property address<input formControlName="address" maxlength="255"></label><label>City<input formControlName="city" maxlength="100"></label><label>State<input formControlName="state" maxlength="2"></label><label>Claim category<select formControlName="filingType"><option>Title Claim</option><option>Lien</option><option>Easement</option><option>Deed Dispute</option></select></label><label>Claimant or owner<input formControlName="claimantName" maxlength="255"></label><label>Issue description<textarea formControlName="notes"></textarea></label><button [disabled]="form.invalid || saving()">{{ saving() ? 'Saving…' : 'Submit claim' }}</button><p *ngIf="error()" role="alert">{{ error() }}</p></form></main>`, styles: [`main{margin:auto;max-width:700px;padding:42px 24px}form{display:grid;gap:16px;margin-top:24px}label{display:grid;gap:6px;font-weight:700}input,select,textarea,button{font:inherit;padding:10px}textarea{min-height:120px}button{background:#5367e8;border:0;color:white;font-weight:700}p{color:#62708a}`] })
export class ClaimCreateComponent {
  private readonly fb = inject(FormBuilder); private readonly api = inject(ClaimApiService); private readonly router = inject(Router); private readonly destroyRef = inject(DestroyRef);
  readonly saving = signal(false); readonly error = signal<string | null>(null); readonly form = this.fb.nonNullable.group({ address: ['', [Validators.required, Validators.maxLength(255)]], city: ['', [Validators.required, Validators.maxLength(100)]], state: ['', [Validators.required, Validators.pattern(/^[a-zA-Z]{2}$/)]], filingType: ['Title Claim', Validators.required], claimantName: [''], notes: [''] });
  submit(): void { if (this.form.invalid || this.saving()) return; this.saving.set(true); const value = this.form.getRawValue(); this.api.createClaim({ ...value, state: value.state.toUpperCase(), legalDescription: null, dateFiled: new Date().toISOString(), riskScore: null, claimantName: value.claimantName || null, notes: value.notes || null, filingType: value.filingType as FilingType }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: claim => void this.router.navigate(['/claims', claim.filingID]), error: error => { this.error.set(error.status === 409 ? 'A duplicate submission was detected. Refresh and check My Claims.' : 'The claim could not be saved.'); this.saving.set(false); } }); }
}
