import { CommonModule } from '@angular/common';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ClaimDetail } from '../../core/models/claim.model';
import { ClaimApiService } from '../../core/services/claim-api.service';

@Component({ standalone: true, imports: [CommonModule, RouterLink], template: `<main><a routerLink="/claims">← My claims</a><p *ngIf="loading()" role="status">Loading claim…</p><p *ngIf="error()" role="alert">{{ error() }}</p><article *ngIf="claim() as item"><p>CLAIM #{{ item.filingID }}</p><h1>{{ item.filingType }} — {{ item.status }}</h1><dl><dt>Property</dt><dd>{{ item.address }}, {{ item.city }}, {{ item.state }}</dd><dt>Claimant/owner</dt><dd>{{ item.claimantName || 'Not supplied' }}</dd><dt>Issue</dt><dd>{{ item.notes || 'Not supplied' }}</dd></dl><h2>Status timeline</h2><ol><li *ngFor="let event of item.statusTimeline"><strong>{{ event.toStatus }}</strong><span>{{ event.transitionedUtc | date:'medium' }}</span><p *ngIf="event.reason">{{ event.reason }}</p></li></ol></article></main>`, styles: [`main{margin:auto;max-width:800px;padding:42px 24px}dl{display:grid;grid-template-columns:150px 1fr;gap:12px}dt{font-weight:700}dd{margin:0}li{border-left:3px solid #5367e8;list-style:none;margin:12px 0;padding:8px 14px}li span{color:#62708a;margin-left:10px}p{color:#62708a}`] })
export class ClaimDetailComponent { private readonly api=inject(ClaimApiService); private readonly route=inject(ActivatedRoute); private readonly destroyRef=inject(DestroyRef); readonly claim=signal<ClaimDetail|null>(null); readonly loading=signal(true); readonly error=signal<string|null>(null); constructor(){const id=Number(this.route.snapshot.paramMap.get('id')); if(!Number.isInteger(id)){this.error.set('Claim not found.');this.loading.set(false);return;} this.api.getClaim(id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:claim=>{this.claim.set(claim);this.loading.set(false)},error:error=>{this.error.set(error.status===404?'Claim not found.':'Unable to load claim.');this.loading.set(false)}});}}
